linpar("A", 200, 8)
linpar("B", 150, 6)
linpar("C", 110, 4.5)
linpar("D", 50, 2)
linpar("E", 40, 1.5)
linpar("F", 20, 0.8)
linpar("G", 50, 2)
linpar("H", 30, 1.2)

def generate():
    
    moveto(G, 0)
    lineto(A, 0)
    lineto(A, B - D)
    lineto(A - C + E, B - D)
    lineto(A - C, B - D + F)
    lineto(A - C, B)
    lineto(0, B)
    lineto(0, H)
    close()
    
    dimlin("A", 0, 0, A, 0, False)
    dimlin("B", 0, 0, 0, B, True)
    dimlin("C", A - C, B, A, B, True)
    dimlin("D", A, B - D, A, B, False)
    dimlin("E", A - C, B - D, A-C+E, B - D, False)
    dimlin("F", A - C, B - D, A - C, B-D+F, True)
    dimlin("G", 0, 0, G, 0, False,64)
    dimlin("H", 0, 0, 0, H, True,64)