;;; TOOLBAR.lisp
;;; Generated by IGEMS Toolbar Generator
;;; Profile: Default
;;; Date: 2026-06-02 08:25:26

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              SYSTEM MENU                                   ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ submnu (TB-SYSBTN (LTF "New") "CORE.New.png" "CORE.New" "Ctrl+N"))
  (TB-BTN submnu (LTF "New") "CORE.New.png" "CORE.New" "Ctrl+N")
  (TB-BTN submnu (LTF "Templates") "CORE.Templates.png" "CORE.Templates" nil)
  (TB-BTN submnu (LTF "Drawing note") "CORE.DrawingNote.png" "CORE.DrawingNote" nil)

(SETQ submnu (TB-SYSBTN (LTF "Open") "CORE.Open.png" "CORE.Open" "Ctrl+O"))
  (TB-BTN submnu (LTF "Open") "CORE.Open.png" "CORE.Open" "Ctrl+O")
  (TB-BTN submnu (LTF "Samples") "CORE.OpenSamples.png" "CORE.OpenSamples" nil)
  (TB-BTN submnu (LTF "Import") "CAD.Import.png" "CAD.Import" "Ctrl+I")
  (TB-BTN submnu (LTF "Recover") "CORE.Recover.png" "CORE.Recover" nil)

(TB-SYSRECENT "CORE.RecentFiles.png")

(TB-SYSBTN (LTF "Save") "CORE.Save.png" "CORE.Save" "Ctrl+S")

(SETQ submnu (TB-SYSBTN (LTF "Save as") "CORE.SaveAs.png" "CORE.SaveAs" "Ctrl+Shift+S"))
  (TB-BTN submnu (LTF "Save as") "CORE.SaveAs.png" "CORE.SaveAs" "Ctrl+Shift+S")
  (TB-BTN submnu (LTF "Save as template") "CORE.SaveTemplate.png" "CORE.SaveTemplate" nil)
  (TB-BTN submnu (LTF "Export") "CORE.Export.png" "CORE.Export" "Ctrl+E")
  (TB-BTN submnu (LTF "Support") "Cam2d2.BugReport.png" "Cam2d2.BugReportSave" nil)

(SETQ submnu (TB-SYSBTN (LTF "Close") "CORE.Close.png" "CORE.Close" "Ctrl+F4"))
  (TB-BTN submnu (LTF "Close") "CORE.Close.png" "CORE.Close" "Ctrl+F4")
  (TB-BTN submnu (LTF "Close all") "CORE.CloseAll.png" "CORE.CloseAll" nil)

(TB-SYSBTN "-")

(SETQ submnu (TB-SYSBTN (LTF "Plot") "CORE.Plot.png" "CORE.Plot" "Ctrl+P"))
  (TB-BTN submnu (LTF "Plot") "CORE.Plot.png" "CORE.Plot" "Ctrl+P")
  (TB-BTN submnu (LTF "Limits") "CORE.Limits.png" "CORE.Limits" nil)
  (TB-BTN submnu (LTF "Dump image") "CORE.DumpImage.png" "CORE.DumpImage" "Ctrl+G")

(SETQ submnu (TB-SYSBTN (LTF "Preferences") "CORE.Preferences.png" "CORE.Preferences" nil))
  (TB-BTN submnu (LTF "Preferences") "CORE.Preferences.png" "CORE.Preferences" nil)
  (TB-BTN submnu (LTF "Password") "CORE.Password.png" "CORE.Password" nil)
  (TB-BTN submnu (LTF "Shortkeys") "CORE.MapShortcuts.png" "CORE.MapShortcuts" nil)
  (TB-BTN submnu "-") ;separator
  (TB-BTN submnu (LTF "Drawing units") "CORE.DrawingUnits.png" "CORE.DrawingUnits" nil)
  (TB-BTN submnu (LTF "Point style") "CAD.PointStyle.png" "CAD.PointStyle" nil)

(TB-SYSBTN (LTF "Subscription") "CORE.Subscription.png" "CORE.License" nil)

(TB-SYSBTN (LTF "About") "CORE.About.png" "CORE.About" nil)

(TB-SYSBTN (LTF "Changelog") "CORE.Changelog.png" "CORE.ChangeLog" nil)

(TB-SYSBTN (LTF "Check for updates") "CORE.CheckForUpdates.png" "CORE.CheckForUpdates" nil)

(TB-SYSBTN (LTF "Help") "CORE.Help.png" "CORE.Help" nil)

(TB-SYSBTN "-")

(TB-SYSBTN (LTF "Express") "Cam2d2.IGEMSExpress.png" "Cam2d2.IGEMSExpress" nil)

(TB-SYSBTN "-")

(TB-SYSBTN (LTF "Exit") "CORE.Exit.png" "CORE.Exit" nil)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              CAD TOOLBAR                                  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ tab (TB-TAB (LTF "CAD")))

  ;; System group
  (TB-BTN tab (LTF "Undo") "CORE.Undo.png" "CORE.Undo" "Ctrl+Z")
  (TB-BTN tab (LTF "Redo") "CORE.Redo.png" "CORE.Redo" "Ctrl+Y")
  (SETQ grp (TB-GRP tab (LTF "System")))
    (TB-BTN grp (LTF "Purge") "CORE.Purge.png" "CORE.Purge" nil)
    (TB-BTN grp (LTF "Status") "CORE.Status.png" "CORE.Status" nil)
    (TB-BTN grp (LTF "Shared folder") "CORE.SharedFolder.png" "CORE.SharedFolder" nil)
    (TB-BTN grp (LTF "Service center") "CORE.ServiceCenter.png" "CORE.ServiceCenter" nil)
    (SETQ submnu (TB-BTN grp (LTF "Save support file") "Cam2d2.BugReport.png" "Cam2d2.BugReport" nil))
      (TB-BTN submnu (LTF "Reset installation") "Cam2d2.Reset.png" "Cam2d2.BugReportRestore" nil)

  ;; Draw group
  (TB-BTN tab (LTF "Line") "CAD.Line.png" "CAD.Line" "L")
  (TB-BTN tab (LTF "Circle") "CAD.Circle.png" "CAD.Circle" "C")
  (TB-BTN tab (LTF "Rectangle") "CAD.Rectangle.png" "CAD.Rectangle" "N")
  (SETQ grp (TB-GRP tab (LTF "Draw")))
    (TB-BTN grp (LTF "Point") "CAD.Point.png" "CAD.Point" "Shift+P")
    (SETQ submnu (TB-BTN grp (LTF "Arc") "CAD.Arc.png" "CAD.Arc" "A"))
      (TB-BTN submnu (LTF "Arc") "CAD.Arc.png" "CAD.Arc" "A")
      (TB-BTN submnu (LTF "Center, start, end") "CAD.ArcCSE.png" "CAD.ArcCSE" nil)
      (TB-BTN submnu (LTF "Start, center, angle") "CAD.ArcSCA.png" "CAD.ArcSCA" nil)
      (TB-BTN submnu (LTF "Start, center, length") "CAD.ArcSCL.png" "CAD.ArcSCL" nil)
      (TB-BTN submnu (LTF "Start, end, angle") "CAD.ArcSEA.png" "CAD.ArcSEA" nil)
      (TB-BTN submnu (LTF "Start, end, direction") "CAD.ArcSED.png" "CAD.ArcSED" nil)
      (TB-BTN submnu (LTF "Start, end, radius") "CAD.ArcSER.png" "CAD.ArcSER" nil)
    (SETQ submnu (TB-BTN grp (LTF "Circle") "CAD.Circle.png" "CAD.Circle" "C"))
      (TB-BTN submnu (LTF "From 2 points") "CAD.Circle2P.png" "CAD.Circle2P" nil)
      (TB-BTN submnu (LTF "From 2 points and radius") "CAD.Circle2PR.png" "CAD.Circle2PR" nil)
      (TB-BTN submnu (LTF "From 3 points") "CAD.Circle3P.png" "CAD.Circle3P" nil)
      (TB-BTN submnu (LTF "Enclosing") "CAD.EnclosingCircle.png" "CAD.EnclosingCircle" nil)
    (SETQ submnu (TB-BTN grp (LTF "Rectangle") "CAD.Rectangle.png" "CAD.Rectangle" "N"))
      (TB-BTN submnu (LTF "Rectangle XYC") "CAD.RectangleXYC.png" "CAD.RectangleXYC" nil)
      (TB-BTN submnu (LTF "Bounding box") "CAD.RectangleBB.png" "CAD.RectangleBB" nil)
    (TB-BTN grp (LTF "Polyline") "CAD.Polyline.png" "CAD.Polyline" "P")
    (TB-BTN grp (LTF "Sketch") "CAD.Sketch.png" "CAD.Sketch" nil)
    (TB-BTN grp (LTF "Spline") "CAD.Spline.png" "CAD.Spline" nil)
    (TB-BTN grp (LTF "Ellipse") "CAD.Ellipse.png" "CAD.Ellipse" "Shift+E")
    (TB-BTN grp (LTF "Solid") "CAD.Solid.png" "CAD.Solid" nil)
    (TB-BTN grp (LTF "Hatch") "CAD.Hatch.png" "CAD.Hatch" nil)

  ;; Shape group
  (TB-BTN tab (LTF "Parametric") "PARAMPART.ParametricShapes.png" "PARAMPART.PythonShapes" nil)
  (TB-BTN tab (LTF "N-gon") "CAD.NGon.png" "CAD.NGon" nil)
  (TB-BTN tab (LTF "Text") "CAD.Text.png" "CAD.Text" "Shift+T")
  (SETQ grp (TB-GRP tab (LTF "Shape")))
    (TB-BTN grp (LTF "Obround") "CAD.Obround.png" "CAD.Obround" nil)
    (TB-BTN grp (LTF "Swell") "CAD.Swell.png" "CAD.Swell" nil)
    (TB-BTN grp (LTF "Unswell") "CAD.Unswell.png" "CAD.Unswell" nil)
    (TB-BTN grp (LTF "Art edge") "CAD.ArtEdge.png" "CAD.ArtEdge" nil)
    (TB-BTN grp (LTF "Puzzle") "CAD.Puzzle.png" "CAD.Puzzle" nil)
    (TB-BTN grp (LTF "Boundary poly") "CAD.BPoly.png" "CAD.BPoly" nil)
    (TB-BTN grp (LTF "Parametric (Deprecated)") "PARAMPART.ParametricShapes.png" "PARAMPART.ParametricShapes" nil)
    (TB-BTN grp (LTF "QR codes") "CAD.BarCode.png" "CAD.BarCode" nil)

  ;; Modify group
  (TB-BTN tab (LTF "Offset") "CAD.Offset.png" "CAD.Offset" "O")
  (TB-BTN tab (LTF "Fillet") "CAD.Fillet.png" "CAD.Fillet" "F")
  (TB-BTN tab (LTF "Trim") "CAD.Trim.png" "CAD.Trim" "T")
  (SETQ grp (TB-GRP tab (LTF "Modify")))
    (TB-BTN grp (LTF "Zero fillet") "CAD.ZeroFillet.png" "CAD.ZeroFillet" "Shift+F")
    (TB-BTN grp (LTF "Chamfer") "CAD.Chamfer.png" "CAD.Chamfer" nil)
    (TB-BTN grp (LTF "Smooth connect") "CAD.SmoothConnect.png" "CAD.SmoothConnect" nil)
    (TB-BTN grp (LTF "Lengthen") "CAD.Lengthen.png" "CAD.Lengthen" nil)
    (TB-BTN grp (LTF "Extend") "CAD.Extend.png" "CAD.Extend" nil)
    (TB-BTN grp (LTF "Boolean") "CAD.Boolean.png" "CAD.Boolean" "B")
    (TB-BTN grp (LTF "Polyline editor") "CAD.PolylineEditor.png" "CAD.PolylineEditor" nil)
    (TB-BTN grp (LTF "Break") "CAD.Break.png" "CAD.Break" nil)
    (TB-BTN grp (LTF "Delete") "CAD.Erase.png" "CAD.Erase" "E")

  ;; Group group
  (TB-BTN tab (LTF "Join") "CAD.Join.png" "CAD.Join" "J")
  (TB-BTN tab (LTF "Explode") "CAD.Explode.png" "CAD.Explode" "X")
  (SETQ grp (TB-GRP tab (LTF "Group")))
    (TB-BTN grp (LTF "Create block") "CORE.Block.png" "CORE.Block" "Ctrl+B")
    (TB-BTN grp (LTF "Insert block") "CORE.Insert.png" "CORE.Insert" nil)
    (TB-BTN grp (LTF "Group") "CAD.Group.png" "CAD.Group" "G")
    (TB-BTN grp (LTF "Save block as .dig") "CORE.WriteBlock.png" "CORE.WriteBlock" nil)
    (TB-BTN grp (LTF "Define attributes") "CAD.AttDef.png" "CAD.AttDef" nil)

  ;; Transform group
  (TB-BTN tab (LTF "Move") "CAD.Move.png" "CAD.Move" "M")
  (TB-BTN tab (LTF "Rotate") "CAD.Rotate.png" "CAD.Rotate" "R")
  (TB-BTN tab (LTF "Copy") "CAD.MultiCopy.png" "CAD.MultiCopy" "Shift+C")
  (SETQ grp (TB-GRP tab (LTF "Transform")))
    (TB-BTN grp (LTF "Mirror") "CAD.Mirror.png" "CAD.Mirror" "Shift+M")
    (TB-BTN grp (LTF "Scale") "CAD.Scale.png" "CAD.Scale" "S")
    (TB-BTN grp (LTF "Reference scale") "CAD.Scale.png" "CAD.QuickScale" nil)
    (TB-BTN grp (LTF "Project") "CAD.Project.png" "CAD.Projection" nil)
    (TB-BTN grp (LTF "Quick move") "CAD.SuperMove.png" "CAD.SuperMove" "Ctrl+M")
    (TB-BTN grp (LTF "Stretch") "CAD.Stretch.png" "CAD.Stretch" nil)
    (TB-BTN grp (LTF "Skew") "CAD.Skew.png" "CAD.Skew" nil)
    (TB-BTN grp (LTF "Array") "CAD.Array.png" "CAD.Array" nil)

  ;; Dimension group
  (TB-BTN tab (LTF "Dimension") "CAD.Dimension.png" "CAD.Dimension" "D")
  (TB-BTN tab (LTF "Linear") "CAD.LinearDimension.png" "CAD.LinearDimension" nil)
  (SETQ grp (TB-GRP tab (LTF "Dimension")))
    (TB-BTN grp (LTF "Diameter") "CAD.DiameterDimension.png" "CAD.DiameterDimension" nil)
    (TB-BTN grp (LTF "Radius") "CAD.RadiusDimension.png" "CAD.RadiusDimension" nil)
    (TB-BTN grp (LTF "Positions") "CAD.DimPos.png" "CAD.DimPos" nil)
    (TB-BTN grp (LTF "Angular dimension") "CAD.AngularDimension.png" "CAD.AngularDimension" nil)
    (TB-BTN grp (LTF "Leader") "CAD.Leader.png" "CAD.Leader" nil)
    (TB-BTN grp (LTF "Dimension style") "CAD.DimStyle.png" "CAD.DimStyle" "Shift+D")

  ;; View group
  (TB-BTN tab (LTF "Extents") "CORE.ZoomExtents.png" "CORE.ZoomExtents" "Ctrl+Shift+E")
  (TB-BTN tab (LTF "Line type") "CORE.LineType.png" "CORE.LineType" nil)
  (SETQ grp (TB-GRP tab (LTF "View")))
    (TB-BTN grp (LTF "Pan") "CORE.Pan.png" "CORE.Pan" "Ctrl+Shift+P")
    (TB-BTN grp (LTF "Zoom") "CORE.Zoom.png" "CORE.Zoom" nil)
    (TB-BTN grp (LTF "Zoom window") "CORE.ZoomWindow.png" "CORE.ZoomWindow" nil)
    (TB-BTN grp (LTF "Zoom object") "CORE.ZoomPart.png" "CORE.ZoomObject" nil)
    (TB-BTN grp (LTF "Color") "CORE.Color.png" "CORE.Color" nil)
    (TB-BTN grp (LTF "Line weight") "CORE.LineWeight.png" "CORE.LineWeight" nil)
    (TB-BTN grp (LTF "Send to back") "CORE.SendToBack.png" "CORE.SendToBack" nil)
    (TB-BTN grp (LTF "Bring to front") "CORE.BringToFront.png" "CORE.BringToFront" nil)

  ;; Info group
  (TB-BTN tab (LTF "Info") "CORE.Info.png" "CORE.Info" "I")
  (TB-BTN tab (LTF "Distance") "CAD.Distance.png" "CAD.Distance" "Ctrl+D")
  (SETQ grp (TB-GRP tab (LTF "Info")))
    (TB-BTN grp (LTF "Id") "CORE.Id.png" "CORE.Id" nil)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              TOOLS TOOLBAR                                ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ tab (TB-TAB (LTF "TOOLS")))

  (IF (MODULES 2)
    (PROGN
  
      ;; CAM tools group
      (TB-BTN tab (LTF "Clean up") "CAMTools.CleanUp.png" "CAMTools.CleanUp" nil)
      (TB-BTN tab (LTF "EdgeFix") "CAMTools.EdgeFix.png" "CAMTools.EdgeFix" nil)
      (TB-BTN tab (LTF "Curvefit") "CAMTools.Curvefit.png" "CAMTools.Curvefit" nil)
      (TB-BTN tab (LTF "Shape rec") "CAMTools.ShapeRecognition.png" "CAMTools.ShapeRecognition" nil)
      (TB-BTN tab (LTF "Analyze") "CAMTools.ContourAnalyzer.png" "CAMTools.ContourAnalyzer" "Shift+A")
      (TB-BTN tab (LTF "Poly joint") "CAMTools.PolyJoint.png" "CAMTools.PolyJoint" nil)
      (SETQ grp (TB-GRP tab (LTF "CAM tools")))
        (TB-BTN grp (LTF "Replace") "CAMTools.ObjectReplace.png" "CAMTools.ObjectReplace" nil)
        (TB-BTN grp (LTF "Boundary scan") "CAMTools.BoundaryScan.png" "CAMTools.BoundaryScan" nil)
        (TB-BTN grp (LTF "Boundary trim") "CAMTools.BoundaryTrim.png" "CAMTools.BoundaryTrim" nil)
        (TB-BTN grp (LTF "Corner cutout") "CAMTools.CornerCutout.png" "CAMTools.CornerCutout" nil)
		(TB-BTN grp (LTF "Slit to line") "CAMTools.SlitToLine.png" "CAMTools.SlitToLine" nil)
        (TB-BTN grp (LTF "Vectorize") "CAMTools.Vectorize.png" "CAMTools.Vectorize" nil)
        (TB-BTN grp (LTF "Divide") "CAMTools.Divide.png" "CAMTools.Divide" nil)
        (TB-BTN grp (LTF "Pocketing") "CAD.Pocketing.png" "CAD.Pocketing" nil)
        (TB-BTN grp (LTF "Convex hull") "CAMTools.ConvexHull.png" "CAMTools.ConvexHull" nil)
        (TB-BTN grp (LTF "Align") "CAMTools.Align.png" "CAMTools.Align" nil)
        (TB-BTN grp (LTF "Dovetail") "CAMTools.Dovetail.png" "CAMTools.Dovetail" nil)
    ))

  (IF (MODULES 3)
    (PROGN
  
      ;; Sign maker group
      (TB-BTN tab (LTF "Type") "SignMaker.FontTracer.png" "SignMaker.FontTracer" nil)
      (TB-BTN tab (LTF "Trace") "ImageTracer.Trace.png" "ImageTracer.Trace" nil)
      (TB-BTN tab (LTF "Etch") "Cam2d2.Etch2.png" "Cam2d2.Etch2" nil)
      (SETQ grp (TB-GRP tab (LTF "Sign maker")))
        (TB-BTN grp (LTF "Shadow extrude") "ShadowExtrude.png" "SignMaker.ShadowExtrude" nil)
        (TB-BTN grp (LTF "Image") "CAD.Image.png" "CAD.Image" nil)
        (TB-BTN grp (LTF "Optimize") "CAD.Optimise.png" "CAD.RescaleImage" nil)
    ))

  (IF (MODULES 8)
    (PROGN
  
      ;; Tiles group
      (TB-BTN tab (LTF "Trim solids") "CAMTools.SolidClip.png" "CAMTools.SolidClip" nil)
      (TB-BTN tab (LTF "Tiles") "SignMaker.TileMaker.png" "SignMaker.TileMaker" nil)
      (TB-BTN tab (LTF "Cut") "NEST.TileCut.png" "NEST.TileCut" nil)
      (SETQ grp (TB-GRP tab (LTF "Tiles")))
  
      ;; Stone group
      (TB-BTN tab (LTF "Parts") "TileMaker.SplitToParts.png" "Cam2d2.InlayParts" nil)
      (TB-BTN tab (LTF "Inlay") "NEST.Inlay.png" "NEST.Inlay" nil)
      (TB-BTN tab (LTF "Pattern") "TileMaker.PatternMatch.png" "Cam2d2.VeinsMatching" nil)
      (SETQ grp (TB-GRP tab (LTF "Stone")))
    ))

  (IF (MODULES 13)
    (PROGN
  
      ;; Vision group
      (TB-BTN tab (LTF "Slab tracer") "Cam2d2.SlabTracer.png" "Cam2d2.SlabTracer" nil)
      (TB-BTN tab (LTF "Snapshot") "Cam2d2.CameraSnapshot2.png" "Cam2d2.CameraSnapshot2" nil)
      (SETQ grp (TB-GRP tab (LTF "Vision")))
        (TB-BTN grp (LTF "Camera manager") "Cam2d2.CameraManager.png" "Cam2d2.CameraManager" nil)
    ))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              CAM TOOLBAR                                  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ tab (TB-TAB (LTF "CAM")))

  (IF (MODULES 4)
    (PROGN
  
      ;; Setup group
      (TB-BTN tab (LTF "Select") "Cam2d2.Material.png" "Cam2d2.MacMat2" "0")
      (SETQ grp (TB-GRP tab (LTF "Setup")))
        (TB-BTN grp (LTF "Install machine from support file") "Cam2d2.BugReport.png" "Cam2d2.MachineISF" nil)
        (TB-BTN grp (LTF "Install machine") "Cam2d2.InstallMachine.png" "Cam2d2.MachineCloud" nil)
  
      ;; Sheet group
      (TB-BTN tab (LTF "Create sheet") "Cam2d2.CreateSheet.png" "Cam2d2.CreateSheet" nil)
      (TB-BTN tab (LTF "Rectangle") "Cam2d2.CreateRectangularSheet.png" "Cam2d2.CreateRectangularSheet" "SHIFT+N")
      (TB-BTN tab (LTF "Register") "Cam2d2.RegisterSheet.png" "Cam2d2.RegisterSheetDB" nil)
      (TB-BTN tab (LTF "Sheets") "Cam2d2.SheetDatabase.png" "Cam2d2.SheetDB" nil)
      (SETQ grp (TB-GRP tab (LTF "Sheet")))
        (TB-BTN grp (LTF "Lock") "Cam2d2.LockSheet.png" "Cam2d2.LockSheet" nil)
        (TB-BTN grp (LTF "Unlock") "Cam2d2.UnlockSheet.png" "Cam2d2.UnlockSheet" nil)
        (TB-BTN grp (LTF "Divide") "Cam2d2.DivideSheet.png" "Cam2d2.DivideSheet" nil)
        (TB-BTN grp (LTF "From hole") "Cam2d2.SubSheet.png" "Cam2d2.SubSheet" nil)
        (TB-BTN grp (LTF "Inventory") "Cam2d2.SheetInventory.png" "Cam2d2.SheetInventory" nil)
        (TB-BTN grp (LTF "History") "Cam2d2.History.png" "Cam2d2.History" nil)
    ))

  ;; Part group
  (TB-BTN tab (LTF "Create") "Cam2d2.CreatePart.png" "Cam2d2.CreatePart" "1")
  (IF (MODULES 4) (TB-BTN tab (LTF "Quality") "Cam2d2.Quality.png" "Cam2d2.Quality" nil))
  (IF (MODULES 10) (TB-BTN tab (LTF "Register") "ORGANIZER.Register.png" "ORGANIZER.Register" nil))
  (IF (MODULES 10) (TB-BTN tab (LTF "Organizer") "ORGANIZER.Organizer.png" "ORGANIZER.Organizer" nil))
  (SETQ grp (TB-GRP tab (LTF "Part")))
    (IF (MODULES 4) (TB-BTN grp (LTF "Tools") "Cam2d2.ToolSetup.png" "Cam2d2.ToolSetup" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "TAC-LAG") "Cam2d2.TaperControl.png" "Cam2d2.TaperControl" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Join") "Cam2d2.JoinParts.png" "Cam2d2.JoinParts" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Split") "Cam2d2.SplitParts.png" "Cam2d2.SplitParts" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Stretch") "Cam2d2.StretchPart.png" "Cam2d2.StretchPart" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Offset") "Cam2d2.OffsetPart.png" "Cam2d2.OffsetPart" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Add other objects") "Cam2d2.AddOtherObjects.png" "Cam2d2.AddOtherObjects" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Center parts") "Cam2d2.CenterParts.png" "Cam2d2.CenterHoles" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Properties") "Cam2d2.PartProperties.png" "Cam2d2.PartProperties" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Browser") "Cam2d2.PartBrowser.png" "Cam2d2.DockedBrowser" "F2"))
    (IF (MODULES 4) (TB-BTN grp (LTF "Part text") "Cam2d2.PartText.png" "Cam2d2.PartText" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Inkjet") "Cam2d2.Inkjet.png" "Cam2d2.Inkjet" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Clone") "Cam2d2.ClonePart.png" "Cam2d2.ClonePart" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Geometry Optimization") "Cam2d2.GeometryOptimization.png" "Cam2d2.GeometryOptimization" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Plasma Contour") "Cam2d2.PlasmaContour.png" "Cam2d2.PlasmaContour" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Speed optimisation") "Cam2d2.SpeedRamping.png" "Cam2d2.SpeedRamping" nil))
    (IF (MODULES 4) (TB-BTN grp (LTF "Find part") "Cam2d2.FindPart.png" "Cam2d2.FindPart" nil))

  (IF (MODULES 6)
    (PROGN
  
      ;; Nest group
      (TB-BTN tab (LTF "Manual") "NEST.BumpNest.png" "NEST.ManualNest" nil)
      (IF (MODULES 7) (TB-BTN tab (LTF "Auto") "NEST.AutoNest.png" "NEST.AutoNest" nil))
      (TB-BTN tab (LTF "Report") "NEST.Report.png" "NEST.Report" nil)
      (SETQ grp (TB-GRP tab (LTF "Nest")))
        (TB-BTN grp (LTF "Quick") "NEST.BumpNest.png" "NEST.BumpNest" "Q")
        (TB-BTN grp (LTF "Glide") "NEST.BumpNestGlide.png" "NEST.BumpNestGlide" nil)
        (TB-BTN grp (LTF "Single") "NEST.SingleNest.png" "NEST.SingleNest" nil)
        (TB-BTN grp (LTF "Rectangle") "NEST.Rectangle.png" "NEST.Rectangle" nil)
        (TB-BTN grp (LTF "Circle") "NEST.Circle.png" "NEST.Circle" nil)
        (IF (MODULES 7) (TB-BTN grp (LTF "Renest") "NEST.ReNest.png" "NEST.RenestSheet" nil))
    ))

  (IF (MODULES 4)
    (PROGN
  
      ;; Toolpath group
      (TB-BTN tab (LTF "Contour") "Cam2d2.ContourCut.png" "Cam2d2.ContourCut" "2")
      (TB-BTN tab (LTF "Quick") "Cam2d2.Quick.png" "Cam2d2.Quick" nil)
      (TB-BTN tab (LTF "Common") "Cam2d2.CommonCutlines.png" "Cam2d2.CommonCutlines" nil)
      (TB-BTN tab (LTF "Marking") "Cam2d2.Marking.png" "Cam2d2.Marking" nil)
      (IF (NOT (MODULES 9)) (TB-BTN tab (LTF "3D-3X") "3D5X.box.png" "Cam2d2.3D5XV2" "F7"))
      (SETQ grp (TB-GRP tab (LTF "Toolpath")))
        (SETQ submnu (TB-BTN grp (LTF "Edit") "Cam2d2.EditPart.png" "Cam2d2.EditPart" nil))
          (TB-BTN submnu (LTF "Edit") "Cam2d2.EditPart.png" "Cam2d2.EditPart" nil)
          (TB-BTN submnu (LTF "Delete") "Cam2d2.RemoveCutting.png" "Cam2d2.RemoveCutting" nil)
          (TB-BTN submnu (LTF "Copy") "Cam2d2.CopyToolpath.png" "Cam2d2.CopyToolpath" nil)
          (TB-BTN submnu (LTF "Clone") "Cam2d2.CloneCutting.png" "Cam2d2.CloneCutting" nil)
          (TB-BTN submnu (LTF "Disconnect") "Cam2d2.DisconnectToolpath.png" "Cam2d2.DisconnectToolpath" nil)
          (TB-BTN submnu (LTF "Connect to part") "Cam2d2.ConnectToPart.png" "Cam2d2.ConnectToPart" nil)
          (TB-BTN submnu (LTF "Break") "Cam2d2.BreakToolpath.png" "Cam2d2.BreakToolpath" nil)
        (TB-BTN grp (LTF "Slit") "Cam2d2.Slit.png" "Cam2d2.Slit" nil)
        (TB-BTN grp (LTF "Holes") "Cam2d2.Holes.png" "Cam2d2.Holes" nil)
        (TB-BTN grp (LTF "Loops") "Cam2d2.MultiLoops.png" "Cam2d2.MultiLoops" nil)
        (TB-BTN grp (LTF "Micro joints") "Cam2d2.MicroJoints.png" "Cam2d2.MicroJoints" nil)
        (TB-BTN grp (LTF "Bridges") "Cam2d2.Bridges.png" "Cam2d2.Bridges" nil)
        (TB-BTN grp (LTF "Chain") "Cam2d2.ChainCutting.png" "Cam2d2.ChainCutting" nil)
        (TB-BTN grp (LTF "Circle cut") "Cam2d2.CircleCut.png" "Cam2d2.CircleCut" nil)
        (TB-BTN grp (LTF "Manual") "Cam2d2.Manual.png" "Cam2d2.Manual" nil)
        (TB-BTN grp (LTF "Cutoff") "Cam2d2.CutOff.png" "Cam2d2.CutOff" nil)
        (TB-BTN grp (LTF "Gridcut") "Cam2d2.GridCut.png" "Cam2d2.GridCut" nil)
        (TB-BTN grp (LTF "Attribute") "Cam2d2.Attribute.png" "Cam2d2.Attribute" nil)
        (TB-BTN grp (LTF "Tool setup") "Cam2d2.ToolpathToolSetup.png" "Cam2d2.ToolpathToolSetup" nil)
        (TB-BTN grp (LTF "Poly lead") "Cam2d2.PolyLead.png" "Cam2d2.PolyLead" nil)
    ))

  (IF (MODULES 9)
    (PROGN
  
      ;; 5-Axis group
      (TB-BTN tab (LTF "Bevel 2D") "Cam2d2.Bevel2D.png" "Cam2d2.Bevel2D" "5")
      (TB-BTN tab (LTF "Bevel cut") "Cam2d2.BevelCut.png" "Cam2d2.BevelCut2" "6")
      (TB-BTN tab (LTF "3D-5X") "CORE.3D5XSamples.png" "Cam2d2.3D5XV2" "F7")
      (SETQ grp (TB-GRP tab (LTF "5-Axis")))
        (TB-BTN grp (LTF "Bevel 3D") "Cam2d2.2DTo3D.png" "Cam2d2.3D5XBEVEL" "SHIFT+5")
        (TB-BTN grp (LTF "Ruled") "Cam2d2.RuledBevel.png" "Cam2d2.RuledBevel3d5x" nil)
        (TB-BTN grp (LTF "Uniform") "Cam2d2.RuledBevelUniform3d5x.png" "Cam2d2.RuledBevelUniform3d5x" nil)
        (TB-BTN grp (LTF "Tilt Cutoff") "Cam2d2.TiltCutoff.png" "Cam2d2.TiltCutoff" nil)
    ))

  (IF (MODULES 4)
    (PROGN
  
      ;; Process group
      (TB-BTN tab (LTF "Quick") "Cam2d2.FastForward.png" "Cam2d2.FastForward" nil)
      (TB-BTN tab (LTF "Order") "Cam2d2.CutOrder.png" "Cam2d2.CutOrder" "3")
      (TB-BTN tab (LTF "Process") "Cam2d2.Process.png" "Cam2d2.Process2" "4")
      (SETQ grp (TB-GRP tab (LTF "Process")))
        (TB-BTN grp (LTF "Cutting parameters") "Cam2d2.CuttingParameters.png" "Cam2d2.CuttingParameters" nil)
        (TB-BTN grp (LTF "Strategy") "Cam2d2.Strategy.png" "Cam2d2.MachineMethod" nil)
        (TB-BTN grp (LTF "Cost estimate") "Cam2d2.CostEstimate.png" "Cam2d2.CostEstimate" nil)
        (IF (MODULES 1) (TB-BTN grp (LTF "NC reader") "DataExchange.NCReader.png" "DataExchange.NCReader" nil))
    ))
