;;; TOOLBAR.lisp
;;; Generated by IGEMS Toolbar Generator
;;; Profile: 3D-5X
;;; Date: 2026-06-02 08:34:23

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              SYSTEM MENU                                   ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(TB-SYSBTN (LTF "New") "CORE.New.png" "New" "Ctrl+N")

(SETQ submnu (TB-SYSBTN (LTF "Open") "CORE.Open.png" "Open" "Ctrl+O"))
  (TB-BTN submnu (LTF "Open") "CORE.Open.png" "Open" "Ctrl+O")
  (TB-BTN submnu (LTF "Samples") "CORE.3D5XSamples.png" "Samples" nil)
  (TB-BTN submnu (LTF "Import") "CAD.Import.png" "ImportFile" "Ctrl+I")

(TB-SYSRECENT "CORE.RecentFiles.png")

(TB-SYSBTN (LTF "Save") "CORE.Save.png" "Save" "Ctrl+S")

(TB-SYSBTN (LTF "Save as") "CORE.SaveAs.png" "SaveAs" "Ctrl+Shift+S")

(TB-SYSBTN (LTF "Export STEP") "3D5X.STEP.png" "STEPEXPORT" "Ctrl+E")

(TB-SYSBTN (LTF "Export STL") "3D5X.STEP.png" "STLEXPORT" nil)

(TB-SYSBTN (LTF "Layer") "CORE.Layer.png" "Layer" nil)

(TB-SYSBTN "-")

(TB-SYSBTN (LTF "Preferences") "CORE.Preferences.png" "Preferences" nil)

(TB-SYSBTN (LTF "Properties") "CORE.Info.png" "Properties" nil)

(TB-SYSBTN (LTF "Print") "CORE.Plot.png" "Print" "Ctrl+P")

(TB-SYSBTN (LTF "Test") "3D5X.Test.png" "Test" nil)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              CAD TOOLBAR                                  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ tab (TB-TAB (LTF "CAD")))

  ;; System group
  (TB-BTN tab (LTF "Undo") "CORE.Undo.png" "Undo" "Ctrl+Z")
  (TB-BTN tab (LTF "Redo") "CORE.Redo.png" "Redo" "Ctrl+Y")
  (SETQ grp (TB-GRP tab (LTF "System")))

  ;; Plane group
  (TB-BTN tab (LTF "Sketch") "3D5X.sketch.png" "Sketch" "S")
  (TB-BTN tab (LTF "Modify") "3D5X.sketch.png" "ModifySketch" nil)
  (SETQ grp (TB-GRP tab (LTF "Plane")))

  ;; Draw group
  (TB-BTN tab (LTF "Line") "CAD.Line.png" "Line" "L")
  (TB-BTN tab (LTF "Arc") "CAD.Arc.png" "Arc" "A")
  (TB-BTN tab (LTF "Circle") "CAD.Circle3P.png" "CircleCR" "C")
  (SETQ grp (TB-GRP tab (LTF "Draw")))
    (TB-BTN grp (LTF "Rectangle") "CAD.Rectangle.png" "Rectangle" "N")
    (TB-BTN grp (LTF "Spline") "CAD.Spline.png" "Spline" "Shift+S")
    (TB-BTN grp (LTF "Text") "CAD.Text.png" "Text" "Shift+T")
    (TB-BTN grp (LTF "Axis") "CAD.axis.png" "Axis" nil)
    (TB-BTN grp (LTF "Spiral") "3D5X.spiral.png" "SpiralMarking" nil)

  ;; Modify group
  (TB-BTN tab (LTF "Extend") "CAD.Extend.png" "Extend" nil)
  (TB-BTN tab (LTF "Project") "CAD.Project.png" "Project" nil)
  (TB-BTN tab (LTF "Zero fillet") "CAD.ZeroFillet.png" "ZeroFillet" "Shift+F")
  (TB-BTN tab (LTF "Trim") "CAD.Trim.png" "Trim" "T")
  (TB-BTN tab (LTF "Join") "CAD.Join.png" "Join3D" nil)
  (TB-BTN tab (LTF "Offset") "CAD.Offset.png" "Offset" nil)
  (SETQ grp (TB-GRP tab (LTF "Modify")))

  ;; Primitives group
  (TB-BTN tab (LTF "Box") "3D5X.box.png" "PrimBox" nil)
  (TB-BTN tab (LTF "Cylinder") "3D5X.cylinder.png" "PrimCylinder" nil)
  (TB-BTN tab (LTF "Cone") "3D5X.cone.png" "PrimCone" nil)
  (SETQ grp (TB-GRP tab (LTF "Primitives")))
    (TB-BTN grp (LTF "Sphere") "3D5X.sphere.png" "PrimSphere" nil)
    (TB-BTN grp (LTF "Surface") "3D5X.Surface.png" "PrimSurface" nil)

  ;; Solids group
  (TB-BTN tab (LTF "Extrude") "3D5X.extrude.png" "Extrude" nil)
  (TB-BTN tab (LTF "Revolve") "3D5X.revolv.png" "Revolve" nil)
  (TB-BTN tab (LTF "Loft") "3D5X.loft.png" "Loft" nil)
  (SETQ grp (TB-GRP tab (LTF "Solids")))
    (TB-BTN grp (LTF "Subtract") "3D5X.subtract.png" "BooleanSubtract" nil)
    (TB-BTN grp (LTF "Union") "3D5X.union.png" "BooleanUnion" nil)
    (TB-BTN grp (LTF "Intersect") "3D5X.intersect.png" "BooleanIntersection" nil)
    (TB-BTN grp (LTF "Chamfer") "3D5X.Chamfer.png" "ChamferBrep" nil)
    (TB-BTN grp (LTF "Fillet") "3D5X.Fillet.png" "FilletBrep" nil)

  ;; Transform group
  (TB-BTN tab (LTF "Move") "CAD.Move.png" "Move" "M")
  (TB-BTN tab (LTF "Copy") "CAD.MultiCopy.png" "Copy" "Shift+C")
  (TB-BTN tab (LTF "Delete") "CAD.Erase.png" "Delete" "E")
  (SETQ grp (TB-GRP tab (LTF "Transform")))
    (TB-BTN grp (LTF "Scale") "CAD.Scale.png" "Scale" nil)
    (TB-BTN grp (LTF "Mirror") "CAD.Mirror.png" "Mirror" "Shift+M")
    (TB-BTN grp (LTF "Polar Array") "CAD.PolarArray.png" "PolarArray" nil)
    (TB-BTN grp (LTF "Rectangular Array") "CAD.Array.png" "RectangularArray" nil)
    (TB-BTN grp (LTF "Explode") "CAD.Explode.png" "Explode" "X")
    (TB-BTN grp (LTF "Fix topology") "" "FixTopology" nil)

  ;; Info group
  (TB-BTN tab (LTF "Measure") "CAD.Distance.png" "Measure" "Ctrl+D")
  (SETQ grp (TB-GRP tab (LTF "Info")))
    (TB-BTN grp (LTF "Id") "CORE.Id.png" "Id" nil)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              TOOLS TOOLBAR                                ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ tab (TB-TAB (LTF "TOOLS")))

  ;; Fixture group
  (TB-BTN tab (LTF "Grid") "3D5X.Fixture.png" "Fixture" nil)
  (TB-BTN tab (LTF "User fixture") "3D5X.UserFixture.png" "UserFixture" nil)
  (SETQ grp (TB-GRP tab (LTF "Fixture")))

  ;; Tools group
  (TB-BTN tab (LTF "Import") "3D5X.import.png" "Import" nil)
  (TB-BTN tab (LTF "Export") "3D5X.export.png" "Export" nil)
  (TB-BTN tab (LTF "Drop curve") "3D5X.DropCurve.png" "DropCurve" nil)
  (TB-BTN tab (LTF "Wrap") "3D5X.Wrap.png" "Wrap" nil)
  (TB-BTN tab (LTF "Section") "3D5X.section.png" "Section" nil)
  (TB-BTN tab (LTF "Slice") "3D5X.slice.png" "MultiSlice" nil)
  (TB-BTN tab (LTF "Unfold") "3D5X.UnfoldSheet.png" "Unfold" nil)
  (SETQ grp (TB-GRP tab (LTF "Tools")))

  ;; Tube group
  (TB-BTN tab (LTF "Design") "3D5X.TUBEDESIGN.png" "DesignTube" nil)
  (TB-BTN tab (LTF "Axis") "3D5X.TUBE.png" "DefineTube" nil)
  (SETQ grp (TB-GRP tab (LTF "Tube")))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                              CAM TOOLBAR                                  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(SETQ tab (TB-TAB (LTF "CAM")))

  ;; Setup group
  (TB-BTN tab (LTF "Select") "Cam2d2.Material.png" "MacMat" "0")
  (TB-BTN tab (LTF "Probe point") "3D5X.ProbePoint.png" "ProbePoint" nil)
  (SETQ grp (TB-GRP tab (LTF "Setup")))

  ;; Align group
  (TB-BTN tab (LTF "Align") "3D5X.Align.png" "Align" nil)
  (TB-BTN tab (LTF "Z height") "3D5X.zposition.png" "zposition" nil)
  (SETQ grp (TB-GRP tab (LTF "Align")))
    (TB-BTN grp (LTF "Rotate") "3D5X.rotate.png" "rotatemodel" nil)
    (TB-BTN grp (LTF "Three points") "3D5X.adjust3p.png" "Adjust3P" nil)
    (TB-BTN grp (LTF "Align objects") "3D5X.AlignObjects.png" "AlignObjects" nil)

  ;; Toolpath group
  (TB-BTN tab (LTF "Curves") "3D5X.contours.png" "Curves" "1")
  (TB-BTN tab (LTF "Toolpath") "3D5X.paths.png" "Toolpath" "2")
  (TB-BTN tab (LTF "Rapids") "3D5X.rapids.png" "HandleRapids" "3")
  (TB-BTN tab (LTF "Auto") "3D5X.paths.auto.png" "AutoToolPath" "4")
  (TB-BTN tab (LTF "Quality") "Cam2d2.Quality.png" "Quality" nil)
  (SETQ grp (TB-GRP tab (LTF "Toolpath")))
    (TB-BTN grp (LTF "Quick") "3D5X.QuickBevel.png" "QuickBevel" nil)

  ;; Part group
  (TB-BTN tab (LTF "Zero point") "3D5X.zeropoint2.png" "ZeroPoint" nil)
  (TB-BTN tab (LTF "Simulate") "3D5X.simulate.png" "Simulate" nil)
  (TB-BTN tab (LTF "Create") "3D5X.CreatePart.png" "CreatePart4" nil)
  (SETQ grp (TB-GRP tab (LTF "Part")))
    (TB-BTN grp (LTF "NC reader") "DataExchange.NCReader.png" "NCReader3D" nil)
    (TB-BTN grp (LTF "Measure points") "3D5X.datapoints.png" "DataPoints" nil)
    (TB-BTN grp (LTF "Stock") "3D5X.stock.png" "Stock2" nil)
    (TB-BTN grp (LTF "Normals") "3D5X.normals.png" "HandleNormals" nil)
